using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Consolonia.Controls
{
    /// <summary>
    /// Icon enum mapping semantic Avalonia icon names that have Unicode equivalents.
    /// </summary>
    public enum IconKind
    {
        // Navigation & UI
        Home,
        Search,
        Settings,
        Info,
        Warning,
        Help,
        Menu,
        MoreHorizontal,
        MoreVertical,
        Refresh,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        ArrowDown,
        ArrowUpLeft,
        ArrowUpRight,
        ArrowDownLeft,
        ArrowDownRight,
        ChevronLeft,
        ChevronRight,
        ChevronUp,
        ChevronDown,
        Play,
        Pause,
        Stop,
        FastForward,
        Rewind,
        Back,
        Forward,
        First,
        Last,

        // Actions
        Add,
        Remove,
        Close,
        Edit,
        Delete,
        Attach,
        Tag,
        Bookmark,
        Share,
        Download,
        Upload,
        Filter,
        Sort,
        Open,
        New,
        Undo,
        Redo,
        Refresh2,
        Reload,
        Sync,
        Cancel,
        Check,
        Cross,
        Plus,
        Minus,
        Maximize,
        Minimize,
        Restore,

        // Communication
        Mail,
        Phone,
        Chat,
        Comment,
        Lock,
        Unlock,
        Bell,
        BellOff,
        Send,
        Receive,
        Reply,
        ReplyAll,
        ReplyForward,

        // Files & Folders
        Folder,
        FolderOpen,
        Document,
        Copy,
        Cut,
        Paste,
        Save,
        Print,
        Archive,
        File,
        FileText,
        FileImage,
        FileVideo,
        FileAudio,
        FilePdf,
        FileZip,
        FileCode,
        SaveAs,
        Export,
        Import,
        Recycle,
        Trashcan,

        // Media
        Camera,
        Video,
        Image,
        Music,
        VolumeUp,
        VolumeDown,
        VolumeMute,
        Microphone,
        Record,
        LivePhoto,
        SkipNext,
        SkipPrevious,
        Shuffle,
        Repeat,
        RepeatOne,

        // Time & Date
        Calendar,
        Clock,
        Alarm,
        Stopwatch,
        Timer,
        Schedule,
        Event,
        Today,
        History,

        // Location & Travel
        Location,
        Map,
        Compass,
        Pin,
        PinOff,
        Navigation,
        Route,
        GPS,

        // Commerce
        ShoppingCart,
        CreditCard,
        Gift,
        Purchase,
        Sale,
        Receipt,

        // Weather
        Sun,
        Moon,
        Cloud,
        Rain,
        Snow,
        Thunderstorm,
        Umbrella,
        Wind,
        Temperature,

        // Technology & Development
        Code,
        Terminal,
        Database,
        Server,
        Network,
        Wifi,
        WifiOff,
        Bluetooth,
        Power,
        PowerButton,
        Battery,
        PluggedIn,

        // User & People
        User,
        Users,
        UserAdd,
        UserRemove,
        Profile,
        Account,
        Group,
        Team,
        Contact,
        Person,

        // Status & Feedback
        Success,
        Error,
        Loading,
        Progress,
        Complete,
        Pending,
        Active,
        Inactive,
        Online,
        Offline,
        Busy,
        Away,

        // Misc Symbols
        Star,
        Heart,
        HeartBroken,
        Key,
        Lightbulb,
        Trophy,
        Flag,
        Globe,
        Eye,
        Question,
        Exclamation,
        Favorite,
        Like,
        Dislike,
        ThumbsUp,
        ThumbsDown,
        Award,
        Certificate,
        Shield,
        Security,
        Private,
        Public
    }
}
