# Repo File Sync configuration
# https://github.com/marketplace/actions/repo-file-sync-action

group: 
  files:
    - source: .github/workflows
      dest: .github/workflows
      deleteOrphaned: true
      exclude: |
        repo-file-sync.yml
    - source: .editorconfig
      dest: .editorconfig
      deleteOrphaned: true
    - source: .gitignore
      dest: .gitignore
      deleteOrphaned: true
    - source: Directory.Build.props
      dest: Directory.Build.props
      deleteOrphaned: true
    - source: Directory.Core.Build.props
      dest: Directory.Core.Build.props
      deleteOrphaned: true
  repos: |
      Consolonia/Consolonia.Labs
      Consolonia/Consolonia.Templates
      Consolonia/Consolonia.AvaloniaEdit
      Consolonia/Consolonia.Blazor
      Consolonia/Edit.NET